### PR TITLE
fix layout of image when either width or height is bounded, but not the other

### LINKED ISSUE #1184: Image should not take `bc.max()` when only width bounded.
Currently the Image widget takes `bc.max`
This means what when you want to have images in a scroll-able horizontal list, the height of the images is `+inf `.
This means that the images are not displayed at all.
When the image is width bounded the image should take into consideration the width/height of the image itself and calculate the correct height from that.

The same should probably be done to height constrained image widgets.

### PR DESCRIPTION
**Pull request by JAicewizard**
This PR fixes #1184 with a more considerate layout function never taking +infinite in size.

### CODE REVIEW

**Review by ForLoveOfCats — CHANGES_REQUESTED** [review]
I'm not qualified to review the unit test but the logic seems sound :+1:

File: druid/src/widget/image.rs [hunk 1]
```diff
@@ -145,8 +145,19 @@ impl<T: Data> Widget<T> for Image {
...
-        if bc.is_width_bounded() {
-            bc.max()
+        // If either the width or height is constrained calculate a value so that the image fits
+        // in the size exactly. If it is unconstrained by both width and height take the size of
+        // the image.
+        if !bc.is_height_bounded() && bc.is_width_bounded() {
+            let mut size = bc.max();
+            let ratio = size.width / self.image_data.x_pixels as f64;
+            size.height = ratio * self.image_data.y_pixels as f64;
+            size
```
[the remark this answers is not in the document]
Comment (JAicewizard) [reply druid/src/widget/image.rs:155]: for readability I moved the bc.max to its own variable `let max = bc.max()`

File: CHANGELOG.md [hunk 2]
```diff
@@ -60,6 +60,7 @@ You can find its changes [documented below](#060---2020-06-01).
 - Allow derivation of lenses for generic types ([#1120]) by [@rjwittams])
 - Switch widget: Toggle animation being window refresh rate dependent ([#1145] by [@ForLoveOfCats])
 - Multi-click on Windows, partial fix for #859 ([#1157] by [@raphlinus])
+- `widget::Imge` now computes the layout correctly when unbound in one direction. ([#1189] by [@JAicewizard])
```
Comment (ForLoveOfCats) [inline CHANGELOG.md:63]: `widget::Imge` should be `widget::Image`

File: CHANGELOG.md [hunk 3]
```diff
@@ -412,7 +414,8 @@ Last release without a changelog :(
 [#1171]: https://github.com/linebender/druid/pull/1171
 [#1172]: https://github.com/linebender/druid/pull/1172
 [#1173]: https://github.com/linebender/druid/pull/1173
-
+[#1186]: https://github.com/linebender/druid/pull/1186
+++
```
Comment (ForLoveOfCats) [inline CHANGELOG.md:418]: The text `++` was added here which messes up the formatting of the next section

File: druid/src/widget/image.rs [hunk 4]
```diff
@@ -145,8 +145,17 @@ impl<T: Data> Widget<T> for Image {
     ) -> Size {
         bc.debug_check("Image");
 
-        if bc.is_width_bounded() {
-            bc.max()
+        // If either the width or height is constrained calculate a value so that the image fits
+        // in the size exactly. If it is unconstrained by both width and height take the size of
+        // the image.
+        if bc.is_width_bounded() && !bc.is_height_bounded() {
+            let max = bc.max();
```
Comment (ForLoveOfCats) [inline druid/src/widget/image.rs:152]: This doesn't have to be defined twice, it can be defined outside both `if` expressions just below the comment

**Review by ForLoveOfCats — DISMISSED** [review]

**Comment by ForLoveOfCats** [comment]
cc @cmyr I think you're the master of the rendering test system, can you take a look at the unit test here?

File: CHANGELOG.md (hunk 3 above)
Comment (JAicewizard) [reply CHANGELOG.md:418]: I need a new keyboard :reallyreallysad: I absolutely love this one but the up arrow also maps to + after a couple hours of use.

File: druid/src/widget/image.rs (hunk 4 above)
Comment (JAicewizard) [reply druid/src/widget/image.rs:152]: Sure, I didnt do it because I only do that when all branches need the variable and we only need it in the first 2.
I will wait for cmyr's review to fix these issues.

File: druid/src/widget/image.rs [hunk 5]
```diff
@@ -438,4 +446,104 @@ mod tests {
...
+            },
+            |target| {
+                // the width should be calculated to be 400.
+                let width = 400;
+                let raw_pixels = target.into_raw();
+                assert_eq!(raw_pixels.len(), 400 * width * 4);
+
+                // Being a height bound widget every row will have no padding at the start and end._id_1
+
+                // The image starts at (0,0), so 200 white and then 200 black.
```
Comment (jneem) [inline druid/src/widget/image.rs:481]: I find the comment a bit misleading, because you're actually testing only the last white-black row.

File: druid/src/widget/image.rs [hunk 6]
```diff
@@ -438,4 +446,104 @@ mod tests {
...
+                let expecting: Vec<u8> = [
+                    vec![255, 255, 255, 255].repeat(200),
+                    vec![0, 0, 0, 255].repeat(200),
+                ]
+                .concat();
+                assert_eq!(raw_pixels[199 * width * 4..200 * width * 4], expecting[..]);
+
+                // The final row of 400 pixels is 200 white and then 200 black.
```
Comment (jneem) [inline druid/src/widget/image.rs:489]: ...and here you're testing the first black-white row.

File: druid/src/widget/image.rs [hunk 7]
```diff
@@ -438,4 +446,104 @@ mod tests {
...
+            },
+            |target| {
+                // the width should be calculated to be 400.
+                let width = 400;
+                let raw_pixels = target.into_raw();
+                assert_eq!(raw_pixels.len(), 400 * width * 4);
+
+                // Being a height bound widget every row will have no padding at the start and end._id_1
+
+                // The image starts at (0,0), so 200 black and then 200 white.
```
Comment (jneem) [inline druid/src/widget/image.rs:531]: white, then black

File: druid/src/widget/image.rs [hunk 8]
```diff
@@ -438,4 +446,104 @@ mod tests {
...
+                let expecting: Vec<u8> = [
+                    vec![255, 255, 255, 255].repeat(200),
+                    vec![0, 0, 0, 255].repeat(200),
+                ]
+                .concat();
+                assert_eq!(raw_pixels[199 * width * 4..200 * width * 4], expecting[..]);
+
+                // The final row of 400 pixels is 200 white and then 200 black.
```
Comment (jneem) [inline druid/src/widget/image.rs:539]: black, then white

**Review by jneem — COMMENTED** [review]
Given that the pixel interpolation and scaling has already been tested, probably it would be enough to just test the image's layout rect? You can look at the layout tests for an example.

**Comment by JAicewizard** [comment]
I made the tests test just the layout, it works well. I tested that the old implementation would indeed fail.

**Comment by JAicewizard** [comment]
@jneem can you remove the `waiting-on-author` label? I think I addressed all the issues raised.

**Comment by jneem** [comment]
Right, sorry for letting this sit. There's a conflict in the CHANGELOG now, but otherwise it looks good to go.

**Review by jneem — APPROVED** [review]

**Review by ForLoveOfCats — APPROVED** [review]
Yeppers! My nits have been addressed :)

**Comment by JAicewizard** [comment]
This took a bit longer than expected, I fixed some bugs with the renaming and behavior changes around the scrollbar and image buffer.
The mechanisms are the same, and I guess we have now already seen the tests actually work in practice :)
github seems to have broken again so I cant tag anyone.
Would be nice to get this merged to be done with it.

File: CHANGELOG.md [hunk 9]
```diff
@@ -95,8 +95,12 @@ You can find its changes [documented below](#060---2020-06-01).
 - Allow derivation of lenses for generic types ([#1120]) by [@rjwittams])
 - Switch widget: Toggle animation being window refresh rate dependent ([#1145] by [@ForLoveOfCats])
 - Multi-click on Windows, partial fix for #859 ([#1157] by [@raphlinus])
+<<<<<<< HEAD
+- `widget::Image` now computes the layout correctly when unbound in one direction. ([#1189] by [@JAicewizard])
+=======
```
Comment (jneem) [inline CHANGELOG.md:100]: Merge conflict?

**Comment by jneem** [comment]
Thanks for your patience on this! I just see a merge conflict on the changelog, but otherwise I'm ready to merge.

**Comment by JAicewizard** [comment]
oops! I should find a way to make vscode not auto-format .MD files, or highlight merge conflicts in vim.
I'm off to bed but I think its safe to say this wont trip one of the tests (fingers crossed).

It was very nice to work on this, I might try to fix more small things once I have time.

**Comment by ForLoveOfCats** [comment]
At some point the number for the PR in the changelog link became incorrect. Later tonight I'm going to take the liberty of fixing that then merge this. This message mostly serves as a note to any other collaborators that this change needs to be made real quick before merging

File: CHANGELOG.md [hunk 10]
```diff
@@ -465,6 +467,7 @@ Last release without a changelog :(
 [#1185]: https://github.com/linebender/druid/pull/1185
 [#1191]: https://github.com/linebender/druid/pull/1191
 [#1092]: https://github.com/linebender/druid/pull/1092
+[#1186]: https://github.com/linebender/druid/pull/1186
```
Comment (ForLoveOfCats) [inline CHANGELOG.md:470]: The number 1186 should be changed to 1189 in both locations

**Review by ForLoveOfCats — CHANGES_REQUESTED** [review]
Well nevermind lol, the allow edits box was unchecked. Very very minor change here and then we can merge I promise

File: CHANGELOG.md (hunk 10 above)
Comment (JAicewizard) [reply CHANGELOG.md]: yup, fixed it, sorry for the amount of simple mistakes in the markdown.
