### PR TITLE
Do not panic in Application::try_global if Application is not created

### LINKED ISSUE #1995: X11: calling Screen::get_monitors panics
```rust
use druid::widget::SizedBox;
use druid::{AppLauncher, Screen, WindowDesc};

pub fn main() {
    Screen::get_monitors();
    let main_window = WindowDesc::new(SizedBox::empty());
    AppLauncher::with_window(main_window)
        .log_to_console()
        .launch(())
        .expect("Failed to launch application");
}
```
error:
```
'Main thread assertion failed 1 != 0', druid-shell/src/util.rs:39:9
```

useful parts of backtrace 
```
   2: druid_shell::util::assert_main_thread
             at /src/druid/druid-shell/src/util.rs:39:9
   3: druid_shell::application::Application::try_global
             at /src/druid/druid-shell/src/application.rs:124:9
   4: druid_shell::backend::x11::screen::get_monitors
             at /src/druid/druid-shell/src/backend/x11/screen.rs:38:37
   5: druid_shell::screen::Screen::get_monitors
             at /src/druid/druid-shell/src/screen.rs:87:9
```

### PR DESCRIPTION
**Pull request by Maan2003**
`Application::try_global` called `assert_main_thread` but before Application is created the main thread is unclaimed.
I think there was no way for `Application::try_global` to return None.

Added `assert_main_thread_or_main_unclaimed` that does not panic if main thread is unclaimed.

Fixes #1995

### CODE REVIEW

File: druid-shell/src/util.rs [hunk 1]
```diff
@@ -43,6 +44,22 @@ pub fn assert_main_thread() {
     }
 }
 
+/// Assert that the current thread is the registered main thread or main thread is not claimed.
+///
+/// # Panics
+///
+/// Panics when called from a non-main thread and main thread is claimed.
+pub fn assert_main_thread_or_main_unclaimed() {
```
Comment (cmyr) [inline druid-shell/src/util.rs:52]: does this need to be public?

File: druid-shell/src/util.rs [hunk 2]
```diff
@@ -32,6 +32,7 @@ fn current_thread_id() -> u64 {
 /// # Panics
 ///
 /// Panics when called from a non-main thread.
+#[allow(dead_code)] // can be unused on some backend
```
Comment (cmyr) [inline druid-shell/src/util.rs:35]: I'd prefer to use either use [`cfg_atr`](https://doc.rust-lang.org/reference/conditional-compilation.html#the-cfg_attr-attribute) to turn this on per-platform, or use `cfg` to only compile this on platforms where it's used.

(I don't like blanket `allow`s like this because you can't tell from lints when something is actually not used anymore)

**Review by cmyr — APPROVED** [review]
This makes sense, a few little thoughts inline!

File: druid-shell/src/util.rs (hunk 1 above)
Comment (Maan2003) [reply druid-shell/src/util.rs:52]: all other functions in util are also public but util is not public. I will make all these `pub(crate)`
