### PR TITLE
Prevent reentrancy in Windows keyboard event handling

### LINKED ISSUE #2026: Reentrancy when handling keyboard events on Windows
Steps to reproduce:

1. On Windows 10, start the Narrator screen reader.
2. Run any program that uses druid-shell. I've tested with the Druid calc example and the druid-shell shello example.
3. Press Alt+Tab.

The following error is displayed in the console window:

```
druid_shell::backend::windows::window: failed to borrow WndState at druid-shell\src\backend\windows\window.rs:805:22
```

Diagnosis: Because of Narrator's keyboard event preprocessing, the application doesn't receive the key-down event for Alt until the Tab key is pressed. So Windows sends the `WM_KILLFOCUS` message while the application is handling the `WM_KEYDOWN` message for Alt. Then, `druid_shell::backend::windows::keyboard::is_last_message` calls `PeekMessageW`, and during that call, Windows handles the pending `WM_KILLFOCUS` message.

### PR DESCRIPTION
**Pull request by mwcampbell**
fixes #2026

### CODE REVIEW

File: druid-shell/src/backend/windows/keyboard.rs [hunk 1]
```diff
@@ -547,17 +550,17 @@ impl KeyboardState {
     /// is likely low, though.
     pub(crate) unsafe fn process_message(
         &mut self,
-        hwnd: HWND,
         msg: UINT,
         wparam: WPARAM,
         lparam: LPARAM,
+        is_last: bool,
```
Comment (raphlinus) [inline druid-shell/src/backend/windows/keyboard.rs:556]: I'm wondering if "is_last_key" might be a better name, because at this place the context that it's keyboard specific is lost.

**Review by raphlinus — APPROVED** [review]
This looks like a good fix, thanks!
