### PR TITLE
Fix localisation stipping in GTK, X11 and macos

### LINKED ISSUE #1864: Localization fails with .utf8 suffixed locales
On my system, by default, the locale is:
```
LANG=fr_FR.utf8
```

If I run a druid UI with it, it fails to localize using fr-FR locales:
```
$ echo $LANG
fr_FR.utf8
$ ./target/debug/rust-ui-druid
DEBUG [druid::localization] available locales [en-US, fr-FR], current en-US
DEBUG [druid::localization] resolved: [en-US]
```

It works fine with `LANG=fr_FR`:
```
$ LANG=fr_FR ./target/debug/rust-ui-druid
DEBUG [druid::localization] available locales [en-US, fr-FR], current fr-FR
DEBUG [druid::localization] resolved: [fr-FR, en-US]
```

It would be nice to:
 - Have more logs so that understanding what happens is easier (e.g which value is really found before any defaulting)
 - Ignore the .utf8 suffix

### PR DESCRIPTION
**Pull request by JAicewizard**
on macos we already strip the modifiers, this extends this to all backends and also stripping the charset.

fixes #1864

### CODE REVIEW

File: druid-shell/src/backend/gtk/application.rs [hunk 1]
```diff
@@ -84,7 +84,11 @@ impl Application {
     }
 
     pub fn get_locale() -> String {
-        glib::get_language_names()[0].as_str().into()
+        let mut locale: String = glib::get_language_names()[0].as_str().into();
```
Comment (ColinPitrat) [inline druid-shell/src/backend/gtk/application.rs:87]: I think it's worth a comment explaining why this is done (locale having one format but type used expecting a different format).

File: druid-shell/src/backend/x11/application.rs [hunk 2]
```diff
@@ -778,14 +778,18 @@ impl Application {
 
         // from gettext manual
         // https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html#Locale-Environment-Variables
-        var_non_empty("LANGUAGE")
+        let mut locale = var_non_empty("LANGUAGE")
```
Comment (ColinPitrat) [inline druid-shell/src/backend/x11/application.rs:781]: Would it be possible to make var_non_empty log some info (ideally at some verbose level if such a thing is available). It can be useful to the user to know which var is used and which value it has. Currently if the variable cannot be parse you just see "en_US".

Comment (JAicewizard) [reply druid-shell/src/backend/x11/application.rs:781]: I will leave this open for whoever is doing the final review. It does hinder readability but I can see its usefulness.

File: druid-shell/src/backend/gtk/application.rs [hunk 3]
```diff
@@ -84,7 +84,12 @@ impl Application {
...
```
Comment (cmyr) [inline druid-shell/src/backend/gtk/application.rs:87]: this index would panic if there `get_language_names()` is empty. Is that possible?

File: druid-shell/src/backend/mac/application.rs [hunk 4]
```diff
@@ -111,7 +111,8 @@ impl Application {
             let locale: id = msg_send![nslocale_class, currentLocale];
             let ident: id = msg_send![locale, localeIdentifier];
             let mut locale = util::from_nsstring(ident);
-            if let Some(idx) = locale.chars().position(|c| c == '@') {
+            // This is done because the locale parsing library we use expects an unicode locale, but these vars have an ISO locale
+            if let Some(idx) = locale.chars().position(|c| c == '.' || c == '@') {
```
Comment (cmyr) [inline druid-shell/src/backend/mac/application.rs:115]: I believe this is okay as-is, because macOS doesn't include encoding in the locale?

File: druid-shell/src/backend/x11/application.rs (hunk 2 above)
Comment (cmyr) [reply druid-shell/src/backend/x11/application.rs:781]: I think this would be welcome, but I'd make it a separate PR.

**Review by cmyr — COMMENTED** [review]
@ColinPitrat can you confirm that this fixes the original issue? It looks like it should, but would like to be sure.

File: druid-shell/src/backend/gtk/application.rs (hunk 3 above)
Comment (JAicewizard) [reply druid-shell/src/backend/gtk/application.rs:87]: `Computes a list of applicable locale names, which can be used to e.g. construct locale-dependent filenames or search paths. The returned list is sorted from most desirable to least desirable and always contains the default locale "C".`

If druid fails to parse the locale it will be "en_US" so this should work in all cases.

File: druid-shell/src/backend/mac/application.rs (hunk 4 above)
Comment (JAicewizard) [reply druid-shell/src/backend/mac/application.rs:115]: I couldnt find any documentation on this. Having the code be the same across the backends seems nice to me. It hasnt caused any problems so far so it should indeed be fine without.

Comment (JAicewizard) [reply druid-shell/src/backend/mac/application.rs]: I left the comment in since I think it still applies and is helpful

**Review by cmyr — APPROVED** [review]
Looks good, thanks!
