### PR TITLE
Fix parse error in formatter example

### LINKED ISSUE #1838: value formatter panic when entering `24,-` as euro amount.
This is customary in dutch, and although it might not be needed for an example to handle all the local variations, it might be good to not panic on unreachable. Rather mark it as invalid or something along those lines.

### PR DESCRIPTION
**Pull request by cmyr**
- closes #1838

### CODE REVIEW

File: druid/examples/value_formatting/src/formatters.rs [hunk 1]
```diff
@@ -173,7 +174,7 @@ impl Formatter<f64> for NaiveCurrencyFormatter {
                 let bad_char = if c1.is_ascii_digit() { other } else { c1 };
                 Validation::failure(CurrencyValidationError::InvalidChar(bad_char))
             }
-            _ => unreachable!(),
+            other => panic!("unexpected: {:?}", other),
```
Comment (JAicewizard) [inline druid/examples/value_formatting/src/formatters.rs:177]: Why `other` vs `_`? Just curious.

Comment (cmyr) [reply druid/examples/value_formatting/src/formatters.rs:177]: Just so that I had a simple binding I could print to see what the failure was. Probably don't need to commit, but seems more useful anyway..

Comment (JAicewizard) [reply druid/examples/value_formatting/src/formatters.rs:177]: ohh haha I see now, I didnt notice you use it too.

**Review by JAicewizard — APPROVED** [review]
Looks good.
Not sure if I'm allowed to approve, but I'm doing it anyways!

**Review by Maan2003 — APPROVED** [review]
Looks good to me!
